## NORMALIZATION PROBLEM:
### In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

In [44]:
import numpy as np

#random 5x5 array
X = np.random.rand(5, 5)

#calculating mean and standard deviation
mean = X.mean()
std_dev = X.std()

#normalization
X_normalized = (X - mean) / std_dev

#saving normalized array as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

#loading array file
X_normalized = np.load('X_normalized.npy')

#print array
print("Normalized 5x5 Array:")
print(X_normalized)

Normalized 5x5 Array:
[[ 0.84456482  1.83270324  0.44612947 -0.69554759 -1.47196921]
 [ 0.21566265 -0.30233987  1.01514053 -0.27400988 -1.14947884]
 [ 0.91646575  1.17134643 -0.6491711   0.6002917  -0.38275029]
 [ 0.0502653  -1.19153337  1.52630548 -0.07736284 -1.53853418]
 [ 1.84197126 -0.28308247 -1.27557236 -1.06664723 -0.1028474 ]]


## DIVISIBLE BY 3 PROBLEM:
### Create the following 10 x 10 ndarray which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy


In [48]:
import numpy as np

#creating array of first 100 integers
numbers = np.arange(1, 101)

#square the integers then make an array
A = numbers ** 2
A = A.reshape((10, 10))

#finding numbers divisible by 3
div_by_3 = A[A % 3 == 0]

#saving result as file
np.save('div_by_3.npy', div_by_3)

#print elements divisible by 3
print("\nElements divisible by 3:")
print(div_by_3)


Elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
